"""initial_schema

Revision ID: 76e1519f1e4a
Revises: 
Create Date: 2026-06-16 22:00:36.904725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e1519f1e4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_movimientos_stock_lote_id'), 'movimientos_stock', ['lote_id'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_orden_id'), 'movimientos_stock', ['orden_id'], unique=False)
    op.create_index(op.f('ix_movimientos_stock_reactivo_id'), 'movimientos_stock', ['reactivo_id'], unique=False)
    op.create_foreign_key(None, 'movimientos_stock', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'movimientos_stock', 'lotes', ['lote_id'], ['id'])
    op.create_foreign_key(None, 'movimientos_stock', 'ordenes', ['orden_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimientos_stock', type_='foreignkey')
    op.drop_constraint(None, 'movimientos_stock', type_='foreignkey')
    op.drop_constraint(None, 'movimientos_stock', type_='foreignkey')
    op.drop_index(op.f('ix_movimientos_stock_reactivo_id'), table_name='movimientos_stock')
    op.drop_index(op.f('ix_movimientos_stock_orden_id'), table_name='movimientos_stock')
    op.drop_index(op.f('ix_movimientos_stock_lote_id'), table_name='movimientos_stock')
    # ### end Alembic commands ###
